### ISSUE TITLE
Google Translate :: 翻译失败: Too Many Requests 

### ISSUE THREAD

**Issue by i-wujiajie** [YiiGuxing/TranslationPlugin#389]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version:

**Comment by YiiGuxing** [comment]
请求过于频繁，请稍候再试。

**Comment by zhongxuebinwin8** [comment]
![image](https://user-images.githubusercontent.com/28047190/76920207-db1bb300-6905-11ea-89a1-7ceaed9a70b4.png)
钩上即可解决

**Comment by italodeandra** [comment]
Hi,

I just started working today, so I just began using the Google Translate and it started showing this same error after the second word I tried to translate.
I don't know why is this happening. Is there anything I can do to debug this behavior?

I also tried the option @zhongxuebinwin8 mentioned, but it didn't make any difference.

**Comment by YiiGuxing** [comment]
@italodeandra I rarely encounter this, does it appear very often? It could be that Google Translate has put some restrictions on your IP address.

**Comment by italodeandra** [comment]
It actually stopped happening and today I could use it normally doing a lot of translations (because I couldn't yesterday). Maybe this happened for no reason at all. My IP wasn't restricted because it happened with only specific languages. But now I can't reproduce it to show.

**Comment by YiiGuxing** [comment]
@italodeandra Since the free Google Translate API is used, I think it will definitely have some restrictions to prevent the API from being abused, and this error is actually a limitation on the frequency of use. I can't guarantee that this Google Translate API will last forever, unless I switch to the paid version of the API.

**Comment by italodeandra** [comment]
So is this because everyone using the plugin is using the same API key? If so, is it possible to let us get our own API key? Same way it is possible with the other providers.

**Comment by YiiGuxing** [comment]
@italodeandra The API uses the same API as translate.google.com, which is free and does not require an API key. a paid version of the API may be added in the future, but due to some restrictions, I am currently unable to apply for an account with Google Cloud and I cannot use it for plugin development and testing.
