### ISSUE TITLE
Migrate to 2021.3 Platform

### ISSUE THREAD

**Issue by dovchinnikov** [YiiGuxing/TranslationPlugin#883]
Hi, in scope of https://youtrack.jetbrains.com/issue/IDEA-277609 the documentation subsystem was rewritten. The new implementation is enabled by default via `documentation.v2` registry key. 

The new implementation does not use `com.intellij.codeInsight.documentation.DocumentationComponent` and dependent APIs (which means `com.intellij.codeInsight.documentation.DocumentationActionProvider` is not used as well).

Please check out the new implementation in https://github.com/JetBrains/intellij-community/tree/master/platform/lang-impl/src/com/intellij/lang/documentation and tell me what APIs are required for your plugin, so I would have time to provide them for you before 2021.3 release.

**Comment by YiiGuxing** [comment]
@dovchinnikov Hi, If possible, I would like you to provide some APIs that would allow the plugin to do the following:
1. Get the documentation data, process it and update it.
2. Easily switch the display of the original documentation and the documentation after processing.
3. Get the selection in the documentation.

Also,  `com.intellij.codeInsight.documentation.DocumentationActionProvider` is not used in the new documentation subsystem, if I am not mistaken, am I able to add custom actions by registering documentation primary group id `Documentation.PrimaryGroup`?

**Comment by dovchinnikov** [comment]
> add custom actions by registering documentation primary group id `Documentation.PrimaryGroup`

Correct. `DocumentationActionProvider#additionalActions(Editor, PsiDocCommentBase, String)` is still used, we'll deal with it later. `DocumentationActionProvider#additionalActions(DocumentationComponent)` is not used, instead you're supposed to add your actions to `Documentation.PrimaryGroup` action group, like: 
```
<action id="$TranslateQuickDocAction"
        class="cn.yiiguxing.plugin.translate.action.TranslateQuickDocSelectionAction"
        use-shortcut-of="$EditorTranslateAction">
    <add-to-group group-id="Documentation.PrimaryGroup"/>
</action>
```

**Comment by dovchinnikov** [comment]
> Get the selection in the documentation.

This one is done by https://github.com/JetBrains/intellij-community/commit/899c6a834d0e0bba6f5852b6f720b7313f4cb024. It will be available in the EAP next week.

**Comment by dovchinnikov** [comment]
> Get the documentation data, process it and update it.

This one is kind of tricky. Your current implementation still works, and I'm hesitant to add another API just for this case. Let's keep it like this for now. I'm also still unsure on which level such API should operate: `DocumentationTarget` (code insight), `DocumentationBrowser` (IDE), or `DocumentationUI` (raw UI).

**Comment by YiiGuxing** [comment]
Thanks for your answer! I verified it again, the translation task is indeed called in a background thread, but it will block the PSI file loading thread for a long time. If I enable automatic translation, the PSI document will not be displayed in the editor until all the documents are translated (this makes me mistakenly think that the UI thread is blocked). 

Since the inline document is generated in the read action, the translation task should not block it. Therefore, I think that the document provider is not the right place for document translation operations.

What do you think of this?

**Comment by niktrop** [comment]
@YiiGuxing I think rendering of inline documentation is implemented like this to avoid "jumping" of the content. The same applies to translated documentation: you either wait for translation to happen before displaying the document, or do translation in background and get some parts of the editor moving because translated documentation inlay have different sizes. Both options are not very nice in terms of UX. For simple rendering the first approach works because it is quite fast, but the delay is still noticeable on very large files.

**Comment by YiiGuxing** [comment]
@niktrop You are right, maybe we can do this: only when the document comment appears in the visible area, can the translation be triggered. This can reduce the distance of "jumping".

**Comment by dovchinnikov** [comment]
Let's keep this thread about preserving the functionality for 2021.3. We can discuss further ways to improve APIs in YouTrack.

**Comment by YiiGuxing** [comment]
> > Get the documentation data, process it and update it.
> 
> This one is kind of tricky. Your current implementation still works, and I'm hesitant to add another API just for this case. Let's keep it like this for now. I'm also still unsure on which level such API should operate: `DocumentationTarget` (code insight), `DocumentationBrowser` (IDE), or `DocumentationUI` (raw UI).

Hi @dovchinnikov,

It would be really nice if you could implement this feature, so I can use this function instead of the document provider to translate the documentation. Because I can't save my document provider is always valid, the documentation providers of other plugins may have priority over my plugin to obtain execution rights, like this: [JetBrains/android - android-xml.xml#L114](https://github.com/JetBrains/android/blob/16d17317f2c44ec46e8cd2180faf9c349d381a06/android/src/org/jetbrains/android/dom/android-xml.xml#L114).

So I hope you will consider implementing this feature, thanks!
